# Generated by Django 2.2.12 on 2020-08-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={},
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='addresses',
            name='password',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='addresses',
            table='users',
        ),
    ]
