# Generated by Django 2.2.12 on 2020-08-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20200806_0902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
    ]
