# Generated by Django 2.2.12 on 2020-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tem_data', models.FloatField()),
                ('hum_data', models.FloatField()),
                ('light_data', models.FloatField()),
                ('control', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
