# Generated by Django 2.2.12 on 2020-05-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0002_auto_20200517_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_values',
            name='sm_data',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
