# Generated by Django 2.2.12 on 2020-05-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0003_data_values_sm_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_values',
            name='fan_ctl',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='data_values',
            name='light_ctl',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='data_values',
            name='water_ctl',
            field=models.BooleanField(),
        ),
    ]
