# Generated by Django 2.2.12 on 2020-06-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0006_auto_20200611_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.BooleanField()),
                ('tem_data', models.FloatField()),
                ('hum_data', models.FloatField()),
                ('light_data', models.FloatField()),
                ('sm_data', models.FloatField()),
                ('co2', models.FloatField()),
                ('led_time', models.IntegerField()),
                ('mintmp', models.IntegerField()),
                ('maxtmp', models.IntegerField()),
                ('pump_time', models.IntegerField()),
            ],
        ),
    ]
