# Generated by Django 2.2.12 on 2020-06-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0007_automaticsys'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticsys',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
