# Generated by Django 2.2.12 on 2020-06-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0009_auto_20200622_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minled', models.IntegerField()),
                ('maxled', models.IntegerField()),
                ('minpump', models.IntegerField()),
                ('maxpump', models.IntegerField()),
            ],
        ),
    ]
