# Generated by Django 2.2.12 on 2020-06-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0010_data_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_standard',
            name='light_avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_standard',
            name='sm_avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
