# Generated by Django 2.2.12 on 2020-06-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0011_auto_20200624_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_standard',
            name='light_avg',
        ),
        migrations.RemoveField(
            model_name='data_standard',
            name='sm_avg',
        ),
        migrations.AddField(
            model_name='automaticsys',
            name='light_avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automaticsys',
            name='sm_avg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
