# Generated by Django 2.2.12 on 2020-07-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0013_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
