# Generated by Django 2.2.12 on 2020-09-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfarm', '0014_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctl_values_1f',
            name='heat_ctl',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ctl_values_2f',
            name='heat_ctl',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
